# Generated by Django 6.0.3 on 2026-04-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='transaction_uuid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
