# Generated by Django 6.0.1 on 2026-01-14 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_blood_group_user_dob_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='core.bus'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_on_duty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('passenger', 'Passenger'), ('driver', 'Driver')], default='passenger', max_length=20),
        ),
    ]
